source 'https://rubygems.org'

gem 'rack'
gem 'json'
gem 'grape', '0.12.0'
gem 'rack-cors'
gem 'grape-entity', '0.4.5'
gem 'will_paginate'
gem 'rack-test'
gem 'rspec'
gem 'dm-mysql-adapter'
gem 'dm-constraints'
gem 'data_mapper'
gem 'dm-transactions'
gem 'time_difference'